"""add agenda_snapshots table

Revision ID: 9f0b92c27ce6
Revises: f47e7977da24
Create Date: 2026-07-07 17:11:26.317149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0b92c27ce6'
down_revision: Union[str, Sequence[str], None] = 'f47e7977da24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('digest', sa.String(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenda_snapshots')
    # ### end Alembic commands ###
