"""cross platform conversations

a user's conversation becomes ONE stream spanning platforms: the event query
index drops its platform column (platform stays on rows as pure provenance),
platform_identities gains the uniqueness the model always claimed (one
platform account binds to one user - the linking flow relies on it), and
link_codes arrives for the chat-first account-linking flow.

fully reversible; no data is transformed, only indexes/constraints/one new
empty table.

Revision ID: ecce34c113d1
Revises: a68de0c288b5
Create Date: 2026-07-08 21:38:35.483177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecce34c113d1'
down_revision: Union[str, Sequence[str], None] = 'a68de0c288b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('conversation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_events_user_platform_id'))
        batch_op.create_index('ix_conversation_events_user_id', ['user_uuid', 'id'], unique=False)

    # defensive dedup before the constraint lands: uniqueness was only ever
    # enforced by application-level check-then-insert, so a dev db could hold
    # dupes - and sqlite batch mode recreates the table, which would fail on
    # them. keep the oldest row per (platform, platform_user_id).
    op.execute("""
        DELETE FROM platform_identities WHERE id NOT IN (
            SELECT MIN(id) FROM platform_identities GROUP BY platform, platform_user_id)
    """)
    with op.batch_alter_table('platform_identities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_platform_identity_platform_user', ['platform', 'platform_user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_identities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_platform_identity_platform_user', type_='unique')

    with op.batch_alter_table('conversation_events', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_events_user_id')
        batch_op.create_index(batch_op.f('ix_conversation_events_user_platform_id'), ['user_uuid', 'platform', 'id'], unique=False)

    op.drop_table('link_codes')
    # ### end Alembic commands ###
