"""baseline schema

Revision ID: f47e7977da24
Revises: 
Create Date: 2026-07-07 11:57:38.303241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47e7977da24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('preferred_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('schedule_preferences', sa.JSON(), nullable=True),
    sa.Column('bot_personality', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('turn_kind', sa.String(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('hit_iteration_cap', sa.Boolean(), nullable=True),
    sa.Column('tool_trace', sa.JSON(), nullable=True),
    sa.Column('final_text_length', sa.Integer(), nullable=True),
    sa.Column('stop_reason', sa.String(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=True),
    sa.Column('total_output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('first_message_id', sa.Integer(), nullable=True),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('ai_instruction', sa.String(), nullable=False),
    sa.Column('weighting', sa.Float(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('core', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('memory_metadata', sa.JSON(), nullable=True),
    sa.Column('reinforced_count', sa.Integer(), nullable=True),
    sa.Column('last_reinforced_at', sa.DateTime(), nullable=True),
    sa.Column('curated_at', sa.DateTime(), nullable=True),
    sa.Column('merged_into', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('platform_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('platform_user_id', sa.String(), nullable=True),
    sa.Column('platform_username', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('compressed_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_history_id', sa.Integer(), nullable=True),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('original_length', sa.Integer(), nullable=True),
    sa.Column('compressed_content', sa.String(), nullable=True),
    sa.Column('compressed_length', sa.Integer(), nullable=True),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_history_id'], ['conversation_history.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compressed_messages')
    op.drop_table('usage_log')
    op.drop_table('platform_identities')
    op.drop_table('memories')
    op.drop_table('conversation_summaries')
    op.drop_table('conversation_history')
    op.drop_table('agent_traces')
    op.drop_table('users')
    # ### end Alembic commands ###
