"""users.pronouns

Revision ID: fa0005de11c0
Revises: a4c8e21f9b63
Create Date: 2026-08-09 18:20:20.794929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0005de11c0'
down_revision: Union[str, Sequence[str], None] = 'a4c8e21f9b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pronouns', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pronouns')
    # ### end Alembic commands ###
